  class Surah {
   final String arabicName;
   final String englishName;
   final String ayaCount;
   final int surahNumber;

   Surah( { required this.surahNumber,

     required this.arabicName,
     required this.englishName,
     required this.ayaCount,
   });


   static List<Surah> recently = [ Surah(arabicName: "الفاتحه", englishName: "Al-Fatiha", ayaCount: '7',surahNumber: 1),
     Surah(arabicName: "الأنبياء", englishName: "Al-Anbiya", ayaCount: '112',surahNumber: 21),
     Surah(arabicName: "الكهف", englishName: "Al-Kahf", ayaCount: '110',surahNumber: 18),
     Surah(arabicName: "يس", englishName: "Ya-Sin", ayaCount: '83',surahNumber: 36),

   ];
  static List<Surah> surahList = [
   Surah(surahNumber: 1, arabicName: "الفاتحه", englishName: "Al-Fatiha", ayaCount: '7'),
   Surah(surahNumber: 2, arabicName: "البقرة", englishName: "Al-Baqarah", ayaCount: '286'),
   Surah(surahNumber: 3, arabicName: "آل عمران", englishName: "Aal-E-Imran", ayaCount: '200'),
   Surah(surahNumber: 4, arabicName: "النساء", englishName: "An-Nisa'", ayaCount: '176'),
   Surah(surahNumber: 5, arabicName: "المائدة", englishName: "Al-Ma'idah", ayaCount: '120'),
   Surah(surahNumber: 6, arabicName: "الأنعام", englishName: "Al-An'am", ayaCount: '165'),
   Surah(surahNumber: 7, arabicName: "الأعراف", englishName: "Al-A'raf", ayaCount: '206'),
   Surah(surahNumber: 8, arabicName: "الأنفال", englishName: "Al-Anfal", ayaCount: '75'),
   Surah(surahNumber: 9, arabicName: "التوبة", englishName: "At-Tawbah", ayaCount: '129'),
   Surah(surahNumber: 10, arabicName: "يونس", englishName: "Yunus", ayaCount: '109'),
   Surah(surahNumber: 11, arabicName: "هود", englishName: "Hud", ayaCount: '123'),
   Surah(surahNumber: 12, arabicName: "يوسف", englishName: "Yusuf", ayaCount: '111'),
   Surah(surahNumber: 13, arabicName: "الرعد", englishName: "Ar-Ra'd", ayaCount: '43'),
   Surah(surahNumber: 14, arabicName: "إبراهيم", englishName: "Ibrahim", ayaCount: '52'),
   Surah(surahNumber: 15, arabicName: "الحجر", englishName: "Al-Hijr", ayaCount: '99'),
   Surah(surahNumber: 16, arabicName: "النحل", englishName: "An-Nahl", ayaCount: '128'),
   Surah(surahNumber: 17, arabicName: "الإسراء", englishName: "Al-Isra", ayaCount: '111'),
   Surah(surahNumber: 18, arabicName: "الكهف", englishName: "Al-Kahf", ayaCount: '110'),
   Surah(surahNumber: 19, arabicName: "مريم", englishName: "Maryam", ayaCount: '98'),
   Surah(surahNumber: 20, arabicName: "طه", englishName: "Ta-Ha", ayaCount: '135'),
   Surah(surahNumber: 21, arabicName: "الأنبياء", englishName: "Al-Anbiya", ayaCount: '112'),
   Surah(surahNumber: 22, arabicName: "الحج", englishName: "Al-Hajj", ayaCount: '78'),
   Surah(surahNumber: 23, arabicName: "المؤمنون", englishName: "Al-Mu'minun", ayaCount: '118'),
   Surah(surahNumber: 24, arabicName: "النّور", englishName: "An-Nur", ayaCount: '64'),
   Surah(surahNumber: 25, arabicName: "الفرقان", englishName: "Al-Furqan", ayaCount: '77'),
   Surah(surahNumber: 26, arabicName: "الشعراء", englishName: "Ash-Shu'ara", ayaCount: '227'),
   Surah(surahNumber: 27, arabicName: "النّمل", englishName: "An-Naml", ayaCount: '93'),
   Surah(surahNumber: 28, arabicName: "القصص", englishName: "Al-Qasas", ayaCount: '88'),
   Surah(surahNumber: 29, arabicName: "العنكبوت", englishName: "Al-Ankabut", ayaCount: '69'),
   Surah(surahNumber: 30, arabicName: "الرّوم", englishName: "Ar-Rum", ayaCount: '60'),
   Surah(surahNumber: 31, arabicName: "لقمان", englishName: "Luqman", ayaCount: '34'),
   Surah(surahNumber: 32, arabicName: "السجدة", englishName: "As-Sajda", ayaCount: '30'),
   Surah(surahNumber: 33, arabicName: "الأحزاب", englishName: "Al-Ahzab", ayaCount: '73'),
   Surah(surahNumber: 34, arabicName: "سبأ", englishName: "Saba", ayaCount: '54'),
   Surah(surahNumber: 35, arabicName: "فاطر", englishName: "Fatir", ayaCount: '45'),
   Surah(surahNumber: 36, arabicName: "يس", englishName: "Ya-Sin", ayaCount: '83'),
   Surah(surahNumber: 37, arabicName: "الصافات", englishName: "As-Saffat", ayaCount: '182'),
   Surah(surahNumber: 38, arabicName: "ص", englishName: "Sad", ayaCount: '88'),
   Surah(surahNumber: 39, arabicName: "الزمر", englishName: "Az-Zumar", ayaCount: '75'),
   Surah(surahNumber: 40, arabicName: "غافر", englishName: "Ghafir", ayaCount: '85'),
   Surah(surahNumber: 41, arabicName: "فصّلت", englishName: "Fussilat", ayaCount: '54'),
   Surah(surahNumber: 42, arabicName: "الشورى", englishName: "Ash-Shura", ayaCount: '53'),
   Surah(surahNumber: 43, arabicName: "الزخرف", englishName: "Az-Zukhruf", ayaCount: '89'),
   Surah(surahNumber: 44, arabicName: "الدّخان", englishName: "Ad-Dukhan", ayaCount: '59'),
   Surah(surahNumber: 45, arabicName: "الجاثية", englishName: "Al-Jathiya", ayaCount: '37'),
   Surah(surahNumber: 46, arabicName: "الأحقاف", englishName: "Al-Ahqaf", ayaCount: '35'),
   Surah(surahNumber: 47, arabicName: "محمد", englishName: "Muhammad", ayaCount: '38'),
   Surah(surahNumber: 48, arabicName: "الفتح", englishName: "Al-Fath", ayaCount: '29'),
   Surah(surahNumber: 49, arabicName: "الحجرات", englishName: "Al-Hujurat", ayaCount: '18'),
   Surah(surahNumber: 50, arabicName: "ق", englishName: "Qaf", ayaCount: '45'),
   Surah(surahNumber: 51, arabicName: "الذاريات", englishName: "Adh-Dhariyat", ayaCount: '60'),
   Surah(surahNumber: 52, arabicName: "الطور", englishName: "At-Tur", ayaCount: '34'),
   Surah(surahNumber: 53, arabicName: "النجم", englishName: "An-Najm", ayaCount: '30'),
   Surah(surahNumber: 54, arabicName: "القمر", englishName: "Al-Qamar", ayaCount: '20'),
   Surah(surahNumber: 55, arabicName: "الرحمن", englishName: "Ar-Rahman", ayaCount: '78'),
   Surah(surahNumber: 56, arabicName: "الواقعة", englishName: "Al-Waqi'a", ayaCount: '96'),
   Surah(surahNumber: 57, arabicName: "الحديد", englishName: "Al-Hadid", ayaCount: '29'),
   Surah(surahNumber: 58, arabicName: "المجادلة", englishName: "Al-Mujadila", ayaCount: '22'),
   Surah(surahNumber: 59, arabicName: "الحشر", englishName: "Al-Hashr", ayaCount: '24'),
   Surah(surahNumber: 60, arabicName: "الممتحنة", englishName: "Al-Mumtahina", ayaCount: '13'),
   Surah(surahNumber: 61, arabicName: "الصف", englishName: "As-Saff", ayaCount: '14'),
   Surah(surahNumber: 62, arabicName: "الجمعة", englishName: "Al-Jumu'a", ayaCount: '11'),
   Surah(surahNumber: 63, arabicName: "المنافقون", englishName: "Al-Munafiqun", ayaCount: '11'),
   Surah(surahNumber: 64, arabicName: "التغابن", englishName: "At-Taghabun", ayaCount: '18'),
   Surah(surahNumber: 65, arabicName: "الطلاق", englishName: "At-Talaq", ayaCount: '12'),
   Surah(surahNumber: 66, arabicName: "التحريم", englishName: "At-Tahrim", ayaCount: '12'),
   Surah(surahNumber: 67, arabicName: "الملك", englishName: "Al-Mulk", ayaCount: '30'),
   Surah(surahNumber: 68, arabicName: "القلم", englishName: "Al-Qalam", ayaCount: '52'),
   Surah(surahNumber: 69, arabicName: "الحاقة", englishName: "Al-Haqqah", ayaCount: '29'),
   Surah(surahNumber: 70, arabicName: "المعارج", englishName: "Al-Ma'arij", ayaCount: '44'),
   Surah(surahNumber: 71, arabicName: "نوح", englishName: "Nuh", ayaCount: '28'),
   Surah(surahNumber: 72, arabicName: "الجن", englishName: "Al-Jinn", ayaCount: '28'),
   Surah(surahNumber: 73, arabicName: "المزّمّل", englishName: "Al-Muzzammil", ayaCount: '20'),
   Surah(surahNumber: 74, arabicName: "المدّثر", englishName: "Al-Muddathir", ayaCount: '56'),
   Surah(surahNumber: 75, arabicName: "القيامة", englishName: "Al-Qiyamah", ayaCount: '40'),
   Surah(surahNumber: 76, arabicName: "الإنسان", englishName: "Al-Insan", ayaCount: '31'),
   Surah(surahNumber: 77, arabicName: "المرسلات", englishName: "Al-Mursalat", ayaCount: '50'),
   Surah(surahNumber: 78, arabicName: "النبأ", englishName: "An-Naba'", ayaCount: '40'),
   Surah(surahNumber: 79, arabicName: "النازعات", englishName: "An-Nazi'at", ayaCount: '46'),
   Surah(surahNumber: 80, arabicName: "عبس", englishName: "Abasa", ayaCount: '29'),
   Surah(surahNumber: 81, arabicName: "التكوير", englishName: "At-Takwir", ayaCount: '15'),
   Surah(surahNumber: 82, arabicName: "الإنفطار", englishName: "Al-Infitar", ayaCount: '19'),
   Surah(surahNumber: 83, arabicName: "المطفّفين", englishName: "Al-Mutaffifin", ayaCount: '36'),
   Surah(surahNumber: 84, arabicName: "الإنشقاق", englishName: "Al-Inshiqaq", ayaCount: '25'),
   Surah(surahNumber: 85, arabicName: "البروج", englishName: "Al-Buruj", ayaCount: '22'),
   Surah(surahNumber: 86, arabicName: "الطارق", englishName: "At-Tariq", ayaCount: '17'),
   Surah(surahNumber: 87, arabicName: "الأعلى", englishName: "Al-A'la", ayaCount: '19'),
   Surah(surahNumber: 88, arabicName: "الغاشية", englishName: "Al-Ghashiyah", ayaCount: '26'),
   Surah(surahNumber: 89, arabicName: "الفجر", englishName: "Al-Fajr", ayaCount: '30'),
   Surah(surahNumber: 90, arabicName: "البلد", englishName: "Al-Balad", ayaCount: '15'),
   Surah(surahNumber: 91, arabicName: "الشمس", englishName: "Ash-Shams", ayaCount: '15'),
   Surah(surahNumber: 92, arabicName: "الليل", englishName: "Al-Lail", ayaCount: '21'),
   Surah(surahNumber: 93, arabicName: "الضحى", englishName: "Ad-Duha", ayaCount: '11'),
   Surah(surahNumber: 94, arabicName: "الشرح", englishName: "Ash-Sharh", ayaCount: '8'),
   Surah(surahNumber: 95, arabicName: "التين", englishName: "At-Tin", ayaCount: '8'),
   Surah(surahNumber: 96, arabicName: "العلق", englishName: "Al-Alaq", ayaCount: '19'),
   Surah(surahNumber: 97, arabicName: "القدر", englishName: "Al-Qadr", ayaCount: '5'),
   Surah(surahNumber: 98, arabicName: "البينة", englishName: "Al-Bayyina", ayaCount: '8'),
   Surah(surahNumber: 99, arabicName: "الزلزلة", englishName: "Az-Zalzalah", ayaCount: '8'),
   Surah(surahNumber: 100, arabicName: "العاديات", englishName: "Al-Adiyat", ayaCount: '11'),
   Surah(surahNumber: 101, arabicName: "القارعة", englishName: "Al-Qari'a", ayaCount: '11'),
   Surah(surahNumber: 102, arabicName: "التكاثر", englishName: "At-Takathur", ayaCount: '8'),
   Surah(surahNumber: 103, arabicName: "العصر", englishName: "Al-Asr", ayaCount: '3'),
   Surah(surahNumber: 104, arabicName: "الهمزة", englishName: "Al-Humazah", ayaCount: '9'),
   Surah(surahNumber: 105, arabicName: "الفيل", englishName: "Al-Fil", ayaCount: '5'),
   Surah(surahNumber: 106, arabicName: "قريش", englishName: "Quraysh", ayaCount: '4'),
   Surah(surahNumber: 107, arabicName: "الماعون", englishName: "Al-Ma'un", ayaCount: '6'),
   Surah(surahNumber: 108, arabicName: "الكوثر", englishName: "Al-Kawthar", ayaCount: '3'),
   Surah(surahNumber: 109, arabicName: "الكافرون", englishName: "Al-Kafirun", ayaCount: '6'),
   Surah(surahNumber: 110, arabicName: "النصر", englishName: "An-Nasr", ayaCount: '3'),
   Surah(surahNumber: 111, arabicName: "المسد", englishName: "Al-Masad", ayaCount: '5'),
   Surah(surahNumber: 112, arabicName: "الإخلاص", englishName: "Al-Ikhlas", ayaCount: '4'),
   Surah(surahNumber: 113, arabicName: "الفلق", englishName: "Al-Falaq", ayaCount: '5'),
   Surah(surahNumber: 114, arabicName: "الناس", englishName: "An-Nas", ayaCount: '6'),];
 }